// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./page/Home.bs.js";
import * as React from "react";
import MetricsJsx from "./page/Metrics.jsx";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

var make = MetricsJsx;

var Metrics = {
  make: make
};

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match && match.hd === "admin") {
    var match$1 = match.tl;
    if (!match$1) {
      return React.createElement(Home.make, {});
    }
    if (match$1.hd === "apps") {
      var match$2 = match$1.tl;
      if (match$2) {
        var match$3 = match$2.tl;
        if (match$3 && match$3.hd === "metrics" && !match$3.tl) {
          return React.createElement(make, {
                      appId: match$2.hd
                    });
        }
        
      }
      
    }
    
  }
  return React.createElement(Home.make, {});
}

var make$1 = App;

export {
  Metrics ,
  make$1 as make,
  
}
/* make Not a pure module */
