// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";

function app(json) {
  return {
          id: Json_decode.field("id", Json_decode.$$int, json),
          name: Json_decode.field("name", Json_decode.string, json),
          slug: Json_decode.field("slug", Json_decode.string, json),
          description: Json_decode.field("description", Json_decode.string, json),
          icon: Json_decode.optional((function (param) {
                  return Json_decode.field("icon", Json_decode.string, param);
                }), json),
          created_at: Json_decode.field("created_at", Json_decode.string, json),
          updated_at: Json_decode.field("updated_at", Json_decode.string, json)
        };
}

function appsResponse(json) {
  return {
          apps: Json_decode.field("apps", (function (param) {
                  return Json_decode.array(app, param);
                }), json)
        };
}

function metric(json) {
  return {
          id: Json_decode.field("id", Json_decode.$$int, json),
          app_id: Json_decode.field("app_id", Json_decode.$$int, json),
          date: Json_decode.field("date", Json_decode.string, json),
          profile_key: Json_decode.field("profile_key", Json_decode.string, json),
          profile_value: Json_decode.field("profile_value", Json_decode.string, json),
          count: Json_decode.field("count", Json_decode.$$int, json),
          created_at: Json_decode.field("created_at", Json_decode.string, json),
          updated_at: Json_decode.field("updated_at", Json_decode.string, json)
        };
}

function metricsResponse(json) {
  return {
          metrics: Json_decode.field("metrics", (function (param) {
                  return Json_decode.array(metric, param);
                }), json)
        };
}

var Decode = {
  app: app,
  appsResponse: appsResponse,
  metric: metric,
  metricsResponse: metricsResponse
};

export {
  Decode ,
  
}
/* No side effect */
